```{r}
# Load libraries
library(data.table)
library(socialmixr)
library(ggplot2)

# Load data
# Use participant data from Neil to include group contacts
dt_contacts <- as.data.table(polymod$contacts) # Contacts
dt_participants <- as.data.table(read.csv("~/Imperial/covimod-gp/data/POLYMOD/participant_neil.csv"))
dt_population <- as.data.table(read.csv("~/Imperial/covimod-gp/data/germany-population-2011.csv"))
```

## Preprocessing
```{r}
# Select German participants 
# Select contacts by German participants
setnames(dt_participants, 
         c("global_id", "participant_gender", "participant_age"), 
         c("part_id", "part_gender", "part_age"))

min_part_id <- min(dt_participants$part_id)
max_part_id <- max(dt_participants$part_id)
dt_contacts <- dt_contacts[part_id >= min_part_id & part_id <= max_part_id]

# Exclude participants with no age information
dt_participants[, part_gender := as.character(part_gender)]
dt_participants[, part_gender := ifelse(part_gender == "", NA, part_gender)]
dt_participants[, part_gender := ifelse(part_gender == "M", "Male", "Female")]
dt_participants <- dt_participants[!is.na(part_age) & !is.na(part_gender)]

# Identify contacts with missing age or gender information
dt_contacts[, cnt_gender := as.character(cnt_gender)]
dt_contacts[, cnt_gender := ifelse(cnt_gender == "", NA, cnt_gender)]
dt_contacts[, cnt_gender := ifelse(cnt_gender == "M", "Male", "Female")]

dt.ambi <- dt_contacts[is.na(cnt_gender)]
dt_contacts <- dt_contacts[!is.na(cnt_gender)]

# Impute exact age with the midpoint between cnt_age_est_min and cnt_age_est_max if it is missing
dt_contacts[is.na(cnt_age_exact), imp_age := round((cnt_age_est_min + cnt_age_est_max) / 2)]
dt_contacts[!is.na(cnt_age_exact), imp_age := cnt_age_exact]

# Rename variables
setnames(dt_contacts, c("imp_age", "cnt_gender"), c("alter_age", "alter_gender"))
setnames(dt_participants, c("part_age", "part_gender"), c("age", "gender"))
```

## Group contacts
```{r}
# Add school contacts and work contacts for each participant
dt_participants[, y_grp := rowSums(.SD, na.rm = T), .SDcols = c("class_size", "work_contacts_nr")]

# Truncate at 60
dt_group <- dt_participants[,.(age, gender, y_grp)]
dt_group[, y_grp := ifelse(y_grp > 60, 60, y_grp)]

# Calculate the total number of group contacts by age and gender
dt_group <- dt_group[, .(y_grp = sum(y_grp)), by = c("age", "gender")]

sum(dt_group$y_grp)
```


## Make contact data.table
```{r}
# Extract relevant columns
dt_contacts <- dt_contacts[, .(part_id, alter_age, alter_gender)]

# Merge contact data with participant data
dt_contacts <- merge(dt_contacts, 
                     dt_participants[, .(part_id, age, gender)], 
                     by = "part_id", 
                     all.x = TRUE)

# Count the total number of age- and gender-specific contacts
dt_contacts <- dt_contacts[, .(y = .N), by = .(age, gender, alter_age, alter_gender)]

# Make a full grid
g <- expand.grid(age = 0:84, 
                 alter_age = 0:84, 
                 gender = c("Male", "Female"), 
                 alter_gender = c("Male", "Female"))

# Merge with grid
dt_contacts <- merge(g, dt_contacts, all.x = TRUE)

# Fill in true zeros and discard missing combinations
tmp <- dt_participants[, .(N = .N), by = .(age, gender)]
dt_contacts <- as.data.table( merge(dt_contacts, tmp, all.x = TRUE) )
dt_contacts[is.na(y) & !is.na(N), y := 0] # True zeros
dt_contacts <- dt_contacts[!is.na(y)]
```

## Make offsets table
```{r}
# Merge contact data with participant data
dt.ambi <- merge(dt.ambi, dt_participants[, .(part_id, age, gender)], by = c("part_id"), all.x = TRUE)

# Count the number of contacts with missing age or gender info
dt.ambi <- dt.ambi[, .(y_ambi = .N), by = .(age, gender)]

# Discard participants with missing age or gender info
dt.ambi <- dt.ambi[!is.na(age) & !is.na(gender)]

# Calculate the total number complete contact records by age and gender
dt.comp <- dt_contacts[, .(y = sum(y), N = unique(N)), by = .(age, gender)]

# Create offset data.table
g <- as.data.table( expand.grid(age = 0:84, gender = c("Male", "Female")) )
dt_offsets <- merge(g, dt.comp, all.x = TRUE)
dt_offsets <- merge(dt_offsets, dt.ambi, all.x = TRUE)
dt_offsets <- merge(dt_offsets, dt_group, all.x = TRUE)

dt_offsets[is.na(y_ambi), y_ambi := 0]
dt_offsets[is.na(y_grp), y_grp := 0]
dt_offsets[is.na(y), y := 0]
dt_offsets[is.na(N), N := 0]

dt_offsets[, S := y / (y + y_ambi + y_grp)]
dt_offsets[is.nan(S), S := 1.0]

dt_offsets <- dt_offsets[, .(age, gender, N, S)]
```

## Create final contact data.table
```{r}
dt_contacts <- merge(dt_contacts, 
                     dt_offsets[, .(age, gender, S)], 
                     by = c("age", "gender"), 
                     all.x = TRUE)
dt_contacts[is.na(S) & !is.na(N), S := 1.0]
dt_contacts[, m := y/N/S]
```

## Visualize (Sanity check)
```{r}
ggplot(dt_contacts, aes(age, alter_age)) + 
  geom_tile(aes(fill = m)) +
  labs(x = "Age of participants", y = "Age of contacts", fill = "Intensity") + 
  scale_x_continuous(limits = c(0 ,84)) + 
  viridis::scale_fill_viridis(option = "H", limits = c(0, 3)) +
  facet_grid(alter_gender ~ gender) + 
  coord_equal(expand = 0) +
  theme_bw() + 
  theme(
    strip.background = element_blank()
  )
```

## Save processed data
```{r}
data <- list(
  contacts = dt_contacts,
  offsets = dt_offsets,
  population = dt_population
)

saveRDS(data, "~/bayes-rate-consistency/data/POLYMOD/polymod_single_age.rds")
```

```{r}
source("../R/stratify_age.R")

dt_contacts <- stratify_age(dt_contacts, name = "alter_age", strat_name = "alter_age_strata")

dt_contacts <- dt_contacts[, .(y = sum(y, na.rm = T),
                               N = mean(N),
                               S = mean(S)), 
                           by = .(age, gender, alter_age_strata, alter_gender)]

data$contacts <- dt_contacts

saveRDS(data, "~/bayes-rate-consistency/data/POLYMOD/polymod_stratify_age.rds")
```

