seed: 1234

data:
  size: 2000
  covid: FALSE
  strata: "COVIMOD"

model:
  name: "2dgp-m52-cd"
  hsgp_binf: 1.5
  hsgp_m1: 20
  hsgp_m2: 20
  chains: 4
  warmup: 500
  sampling: 1500
  max_treedepth: 13
